#!/usr/bin/perl

use strict;
use warnings;
use DBI;
use CGI qw(fatals to browser);
use CGI qw/:standard *table/;
use CGI::Ajax;

my $dsn = 'DBI:mysql:YTD:localhost';
my $db_user_name = 'root';
my $db_password = 'xxxxxxx';
my $dbh = DBI -> connect ($dsn, $db_user_name, $db_password) or return '<html>Error in SQL connection     (line ..)</html>';
my $Chapt;
my $AID;   my @Lvl; my $i; my @LVL;
if(param){$Chapt = param('Chapt'),$AID = param('AID');}
my $cgi = new CGI;
my $pjx = new CGI::Ajax(
                                'AddFind' => \&AddFind,
                        );

print $pjx->build_html( $cgi, \&HTML);

sub AddFind{
my $rtn;
my $a = shift;
my $b = shift;
my $c = shift;
my $d = shift;
my $e = shift;
 use DBI;
        my $dsn = 'DBI:mysql:YTD:localhost';
        my $db_user_name = 'root';
        my $db_password = 'sh7XclC';
        my $dbh = DBI -> connect ($dsn, $db_user_name, $db_password) or die "error can\'t connect to DB";
	my $query = "insert into findings (AID,Chapts,FID,Finding,Level,STAtus) values (?,?,?,?,?,'Open')";
	my $sth = $dbh -> prepare ($query);
	$sth -> execute ($d,$c,$e,$a,$b);

$rtn = "Returned value is $a and $b and $c and $d and $e";
$sth->finish;
$dbh -> disconnect;

return($rtn);
}

sub HTML{
my $PID;
my @Lvl = ('1','2','3');
my $fid = `date +%s`;
chomp ($fid);
my $out =<<EOHTML;

<html>
 <HEAD>

    <title>LineMaintenanceAssistant</title>
        <link rel="stylesheet" type="text/css" href="/lma.css" />
        <style>
        font-family: helvetica;
        font-size: 10pt;
        button:hover {color:red;}
        </style>

</HEAD>

                                <BODY>
<table>
 <tr><td> Enter Finding for Chapter $Chapt PID $fid $AID<br></td></tr>
<tr><td><TEXTAREA type = "text" id = "AdFin$fid" rows = "10" COLS = "40"></TEXTAREA></td></tr>
<tr><td>Select Finding Level<br>
<select id='LVL'>
        <option value = "1">1</option>
       <option value = "2">2</option>
       <option value = "3">3</option>
        </select></td></tr>
<div id = 'main'>
<tr><td>
<button OnClick="AddFind(['AdFin$fid','LVL','ID','AID','FID'],['main']);"align=center'>Add</button>

</td></tr>
</table>
</div>
</BODY>
</html>

<div id = 'ID'>$Chapt</div>
<div id = 'FID'>$fid</div>
<div id = 'AID'>$AID</div>
EOHTML
return ($out);
}

